package com.back.chuilun.entity;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_id
     *
     * @mbg.generated
     */
    private Long accId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_name
     *
     * @mbg.generated
     */
    private String accName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_createtime
     *
     * @mbg.generated
     */
    private Long accCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_createman
     *
     * @mbg.generated
     */
    private String accCreateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_password
     *
     * @mbg.generated
     */
    private String accPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_updatetime
     *
     * @mbg.generated
     */
    private Long accUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_updateman
     *
     * @mbg.generated
     */
    private String accUpdateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_spare
     *
     * @mbg.generated
     */
    private String accSpare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_id
     *
     * @return the value of account.acc_id
     *
     * @mbg.generated
     */
    public Long getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_id
     *
     * @param accId the value for account.acc_id
     *
     * @mbg.generated
     */
    public void setAccId(Long accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_name
     *
     * @return the value of account.acc_name
     *
     * @mbg.generated
     */
    public String getAccName() {
        return accName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_name
     *
     * @param accName the value for account.acc_name
     *
     * @mbg.generated
     */
    public void setAccName(String accName) {
        this.accName = accName == null ? null : accName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.role_name
     *
     * @return the value of account.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.role_name
     *
     * @param roleName the value for account.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_createtime
     *
     * @return the value of account.acc_createtime
     *
     * @mbg.generated
     */
    public Long getAccCreatetime() {
        return accCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_createtime
     *
     * @param accCreatetime the value for account.acc_createtime
     *
     * @mbg.generated
     */
    public void setAccCreatetime(Long accCreatetime) {
        this.accCreatetime = accCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_createman
     *
     * @return the value of account.acc_createman
     *
     * @mbg.generated
     */
    public String getAccCreateman() {
        return accCreateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_createman
     *
     * @param accCreateman the value for account.acc_createman
     *
     * @mbg.generated
     */
    public void setAccCreateman(String accCreateman) {
        this.accCreateman = accCreateman == null ? null : accCreateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_password
     *
     * @return the value of account.acc_password
     *
     * @mbg.generated
     */
    public String getAccPassword() {
        return accPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_password
     *
     * @param accPassword the value for account.acc_password
     *
     * @mbg.generated
     */
    public void setAccPassword(String accPassword) {
        this.accPassword = accPassword == null ? null : accPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_updatetime
     *
     * @return the value of account.acc_updatetime
     *
     * @mbg.generated
     */
    public Long getAccUpdatetime() {
        return accUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_updatetime
     *
     * @param accUpdatetime the value for account.acc_updatetime
     *
     * @mbg.generated
     */
    public void setAccUpdatetime(Long accUpdatetime) {
        this.accUpdatetime = accUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_updateman
     *
     * @return the value of account.acc_updateman
     *
     * @mbg.generated
     */
    public String getAccUpdateman() {
        return accUpdateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_updateman
     *
     * @param accUpdateman the value for account.acc_updateman
     *
     * @mbg.generated
     */
    public void setAccUpdateman(String accUpdateman) {
        this.accUpdateman = accUpdateman == null ? null : accUpdateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_spare
     *
     * @return the value of account.acc_spare
     *
     * @mbg.generated
     */
    public String getAccSpare() {
        return accSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_spare
     *
     * @param accSpare the value for account.acc_spare
     *
     * @mbg.generated
     */
    public void setAccSpare(String accSpare) {
        this.accSpare = accSpare == null ? null : accSpare.trim();
    }
}