package com.back.chuilun.entity;

public class Bannercontrol {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_id
     *
     * @mbg.generated
     */
    private Integer bannerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_editor
     *
     * @mbg.generated
     */
    private String bannerEditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_url
     *
     * @mbg.generated
     */
    private String bannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_status
     *
     * @mbg.generated
     */
    private Integer bannerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_createtime
     *
     * @mbg.generated
     */
    private Long bannerCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_updatetime
     *
     * @mbg.generated
     */
    private Long bannerUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_createman
     *
     * @mbg.generated
     */
    private String bannerCreateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_updateman
     *
     * @mbg.generated
     */
    private String bannerUpdateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_sor
     *
     * @mbg.generated
     */
    private Integer bannerSor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_spare
     *
     * @mbg.generated
     */
    private String bannerSpare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannercontrol.banner_pic
     *
     * @mbg.generated
     */
    private byte[] bannerPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_id
     *
     * @return the value of bannercontrol.banner_id
     *
     * @mbg.generated
     */
    public Integer getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_id
     *
     * @param bannerId the value for bannercontrol.banner_id
     *
     * @mbg.generated
     */
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_editor
     *
     * @return the value of bannercontrol.banner_editor
     *
     * @mbg.generated
     */
    public String getBannerEditor() {
        return bannerEditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_editor
     *
     * @param bannerEditor the value for bannercontrol.banner_editor
     *
     * @mbg.generated
     */
    public void setBannerEditor(String bannerEditor) {
        this.bannerEditor = bannerEditor == null ? null : bannerEditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_url
     *
     * @return the value of bannercontrol.banner_url
     *
     * @mbg.generated
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_url
     *
     * @param bannerUrl the value for bannercontrol.banner_url
     *
     * @mbg.generated
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl == null ? null : bannerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_status
     *
     * @return the value of bannercontrol.banner_status
     *
     * @mbg.generated
     */
    public Integer getBannerStatus() {
        return bannerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_status
     *
     * @param bannerStatus the value for bannercontrol.banner_status
     *
     * @mbg.generated
     */
    public void setBannerStatus(Integer bannerStatus) {
        this.bannerStatus = bannerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_createtime
     *
     * @return the value of bannercontrol.banner_createtime
     *
     * @mbg.generated
     */
    public Long getBannerCreatetime() {
        return bannerCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_createtime
     *
     * @param bannerCreatetime the value for bannercontrol.banner_createtime
     *
     * @mbg.generated
     */
    public void setBannerCreatetime(Long bannerCreatetime) {
        this.bannerCreatetime = bannerCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_updatetime
     *
     * @return the value of bannercontrol.banner_updatetime
     *
     * @mbg.generated
     */
    public Long getBannerUpdatetime() {
        return bannerUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_updatetime
     *
     * @param bannerUpdatetime the value for bannercontrol.banner_updatetime
     *
     * @mbg.generated
     */
    public void setBannerUpdatetime(Long bannerUpdatetime) {
        this.bannerUpdatetime = bannerUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_createman
     *
     * @return the value of bannercontrol.banner_createman
     *
     * @mbg.generated
     */
    public String getBannerCreateman() {
        return bannerCreateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_createman
     *
     * @param bannerCreateman the value for bannercontrol.banner_createman
     *
     * @mbg.generated
     */
    public void setBannerCreateman(String bannerCreateman) {
        this.bannerCreateman = bannerCreateman == null ? null : bannerCreateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_updateman
     *
     * @return the value of bannercontrol.banner_updateman
     *
     * @mbg.generated
     */
    public String getBannerUpdateman() {
        return bannerUpdateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_updateman
     *
     * @param bannerUpdateman the value for bannercontrol.banner_updateman
     *
     * @mbg.generated
     */
    public void setBannerUpdateman(String bannerUpdateman) {
        this.bannerUpdateman = bannerUpdateman == null ? null : bannerUpdateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_sor
     *
     * @return the value of bannercontrol.banner_sor
     *
     * @mbg.generated
     */
    public Integer getBannerSor() {
        return bannerSor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_sor
     *
     * @param bannerSor the value for bannercontrol.banner_sor
     *
     * @mbg.generated
     */
    public void setBannerSor(Integer bannerSor) {
        this.bannerSor = bannerSor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_spare
     *
     * @return the value of bannercontrol.banner_spare
     *
     * @mbg.generated
     */
    public String getBannerSpare() {
        return bannerSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_spare
     *
     * @param bannerSpare the value for bannercontrol.banner_spare
     *
     * @mbg.generated
     */
    public void setBannerSpare(String bannerSpare) {
        this.bannerSpare = bannerSpare == null ? null : bannerSpare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannercontrol.banner_pic
     *
     * @return the value of bannercontrol.banner_pic
     *
     * @mbg.generated
     */
    public byte[] getBannerPic() {
        return bannerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannercontrol.banner_pic
     *
     * @param bannerPic the value for bannercontrol.banner_pic
     *
     * @mbg.generated
     */
    public void setBannerPic(byte[] bannerPic) {
        this.bannerPic = bannerPic;
    }
}