package com.back.chuilun.entity;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbg.generated
     */
    private Long messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.works_name
     *
     * @mbg.generated
     */
    private String worksName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.visit_name
     *
     * @mbg.generated
     */
    private String visitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mstatus
     *
     * @mbg.generated
     */
    private Integer mstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.editor
     *
     * @mbg.generated
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createman
     *
     * @mbg.generated
     */
    private String createman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.spare
     *
     * @mbg.generated
     */
    private String spare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbg.generated
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.works_name
     *
     * @return the value of message.works_name
     *
     * @mbg.generated
     */
    public String getWorksName() {
        return worksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.works_name
     *
     * @param worksName the value for message.works_name
     *
     * @mbg.generated
     */
    public void setWorksName(String worksName) {
        this.worksName = worksName == null ? null : worksName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.visit_name
     *
     * @return the value of message.visit_name
     *
     * @mbg.generated
     */
    public String getVisitName() {
        return visitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.visit_name
     *
     * @param visitName the value for message.visit_name
     *
     * @mbg.generated
     */
    public void setVisitName(String visitName) {
        this.visitName = visitName == null ? null : visitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mstatus
     *
     * @return the value of message.mstatus
     *
     * @mbg.generated
     */
    public Integer getMstatus() {
        return mstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mstatus
     *
     * @param mstatus the value for message.mstatus
     *
     * @mbg.generated
     */
    public void setMstatus(Integer mstatus) {
        this.mstatus = mstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_time
     *
     * @return the value of message.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_time
     *
     * @param updateTime the value for message.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.editor
     *
     * @return the value of message.editor
     *
     * @mbg.generated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.editor
     *
     * @param editor the value for message.editor
     *
     * @mbg.generated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createman
     *
     * @return the value of message.createman
     *
     * @mbg.generated
     */
    public String getCreateman() {
        return createman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createman
     *
     * @param createman the value for message.createman
     *
     * @mbg.generated
     */
    public void setCreateman(String createman) {
        this.createman = createman == null ? null : createman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.spare
     *
     * @return the value of message.spare
     *
     * @mbg.generated
     */
    public String getSpare() {
        return spare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.spare
     *
     * @param spare the value for message.spare
     *
     * @mbg.generated
     */
    public void setSpare(String spare) {
        this.spare = spare == null ? null : spare.trim();
    }
}