package com.back.chuilun.entity;

public class Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_id
     *
     * @mbg.generated
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_name
     *
     * @mbg.generated
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.fatherid
     *
     * @mbg.generated
     */
    private Integer fatherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_url
     *
     * @mbg.generated
     */
    private String modelUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_createtime
     *
     * @mbg.generated
     */
    private Long modelCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_createman
     *
     * @mbg.generated
     */
    private String modelCreateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_updatetime
     *
     * @mbg.generated
     */
    private Long modelUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_updateman
     *
     * @mbg.generated
     */
    private String modelUpdateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_spare
     *
     * @mbg.generated
     */
    private String modelSpare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_id
     *
     * @return the value of model.model_id
     *
     * @mbg.generated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_id
     *
     * @param modelId the value for model.model_id
     *
     * @mbg.generated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_name
     *
     * @return the value of model.model_name
     *
     * @mbg.generated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_name
     *
     * @param modelName the value for model.model_name
     *
     * @mbg.generated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.fatherid
     *
     * @return the value of model.fatherid
     *
     * @mbg.generated
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.fatherid
     *
     * @param fatherid the value for model.fatherid
     *
     * @mbg.generated
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_url
     *
     * @return the value of model.model_url
     *
     * @mbg.generated
     */
    public String getModelUrl() {
        return modelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_url
     *
     * @param modelUrl the value for model.model_url
     *
     * @mbg.generated
     */
    public void setModelUrl(String modelUrl) {
        this.modelUrl = modelUrl == null ? null : modelUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_createtime
     *
     * @return the value of model.model_createtime
     *
     * @mbg.generated
     */
    public Long getModelCreatetime() {
        return modelCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_createtime
     *
     * @param modelCreatetime the value for model.model_createtime
     *
     * @mbg.generated
     */
    public void setModelCreatetime(Long modelCreatetime) {
        this.modelCreatetime = modelCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_createman
     *
     * @return the value of model.model_createman
     *
     * @mbg.generated
     */
    public String getModelCreateman() {
        return modelCreateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_createman
     *
     * @param modelCreateman the value for model.model_createman
     *
     * @mbg.generated
     */
    public void setModelCreateman(String modelCreateman) {
        this.modelCreateman = modelCreateman == null ? null : modelCreateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_updatetime
     *
     * @return the value of model.model_updatetime
     *
     * @mbg.generated
     */
    public Long getModelUpdatetime() {
        return modelUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_updatetime
     *
     * @param modelUpdatetime the value for model.model_updatetime
     *
     * @mbg.generated
     */
    public void setModelUpdatetime(Long modelUpdatetime) {
        this.modelUpdatetime = modelUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_updateman
     *
     * @return the value of model.model_updateman
     *
     * @mbg.generated
     */
    public String getModelUpdateman() {
        return modelUpdateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_updateman
     *
     * @param modelUpdateman the value for model.model_updateman
     *
     * @mbg.generated
     */
    public void setModelUpdateman(String modelUpdateman) {
        this.modelUpdateman = modelUpdateman == null ? null : modelUpdateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_spare
     *
     * @return the value of model.model_spare
     *
     * @mbg.generated
     */
    public String getModelSpare() {
        return modelSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_spare
     *
     * @param modelSpare the value for model.model_spare
     *
     * @mbg.generated
     */
    public void setModelSpare(String modelSpare) {
        this.modelSpare = modelSpare == null ? null : modelSpare.trim();
    }
}