package com.back.chuilun.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_createtime
     *
     * @mbg.generated
     */
    private Long roleCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_createman
     *
     * @mbg.generated
     */
    private String roleCreateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_messagestatus
     *
     * @mbg.generated
     */
    private Integer roleMessagestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_wroksstatus
     *
     * @mbg.generated
     */
    private Integer roleWroksstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_bannerstatus
     *
     * @mbg.generated
     */
    private Integer roleBannerstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_studiostatus
     *
     * @mbg.generated
     */
    private Integer roleStudiostatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_secpotstatus
     *
     * @mbg.generated
     */
    private Integer roleSecpotstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_roadstatus
     *
     * @mbg.generated
     */
    private Integer roleRoadstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.account_status
     *
     * @mbg.generated
     */
    private Integer accountStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_spare
     *
     * @mbg.generated
     */
    private String roleSpare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_portfolio
     *
     * @mbg.generated
     */
    private Integer rolePortfolio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_createtime
     *
     * @return the value of role.role_createtime
     *
     * @mbg.generated
     */
    public Long getRoleCreatetime() {
        return roleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_createtime
     *
     * @param roleCreatetime the value for role.role_createtime
     *
     * @mbg.generated
     */
    public void setRoleCreatetime(Long roleCreatetime) {
        this.roleCreatetime = roleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_createman
     *
     * @return the value of role.role_createman
     *
     * @mbg.generated
     */
    public String getRoleCreateman() {
        return roleCreateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_createman
     *
     * @param roleCreateman the value for role.role_createman
     *
     * @mbg.generated
     */
    public void setRoleCreateman(String roleCreateman) {
        this.roleCreateman = roleCreateman == null ? null : roleCreateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_messagestatus
     *
     * @return the value of role.role_messagestatus
     *
     * @mbg.generated
     */
    public Integer getRoleMessagestatus() {
        return roleMessagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_messagestatus
     *
     * @param roleMessagestatus the value for role.role_messagestatus
     *
     * @mbg.generated
     */
    public void setRoleMessagestatus(Integer roleMessagestatus) {
        this.roleMessagestatus = roleMessagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_wroksstatus
     *
     * @return the value of role.role_wroksstatus
     *
     * @mbg.generated
     */
    public Integer getRoleWroksstatus() {
        return roleWroksstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_wroksstatus
     *
     * @param roleWroksstatus the value for role.role_wroksstatus
     *
     * @mbg.generated
     */
    public void setRoleWroksstatus(Integer roleWroksstatus) {
        this.roleWroksstatus = roleWroksstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_bannerstatus
     *
     * @return the value of role.role_bannerstatus
     *
     * @mbg.generated
     */
    public Integer getRoleBannerstatus() {
        return roleBannerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_bannerstatus
     *
     * @param roleBannerstatus the value for role.role_bannerstatus
     *
     * @mbg.generated
     */
    public void setRoleBannerstatus(Integer roleBannerstatus) {
        this.roleBannerstatus = roleBannerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_studiostatus
     *
     * @return the value of role.role_studiostatus
     *
     * @mbg.generated
     */
    public Integer getRoleStudiostatus() {
        return roleStudiostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_studiostatus
     *
     * @param roleStudiostatus the value for role.role_studiostatus
     *
     * @mbg.generated
     */
    public void setRoleStudiostatus(Integer roleStudiostatus) {
        this.roleStudiostatus = roleStudiostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_secpotstatus
     *
     * @return the value of role.role_secpotstatus
     *
     * @mbg.generated
     */
    public Integer getRoleSecpotstatus() {
        return roleSecpotstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_secpotstatus
     *
     * @param roleSecpotstatus the value for role.role_secpotstatus
     *
     * @mbg.generated
     */
    public void setRoleSecpotstatus(Integer roleSecpotstatus) {
        this.roleSecpotstatus = roleSecpotstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_roadstatus
     *
     * @return the value of role.role_roadstatus
     *
     * @mbg.generated
     */
    public Integer getRoleRoadstatus() {
        return roleRoadstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_roadstatus
     *
     * @param roleRoadstatus the value for role.role_roadstatus
     *
     * @mbg.generated
     */
    public void setRoleRoadstatus(Integer roleRoadstatus) {
        this.roleRoadstatus = roleRoadstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.account_status
     *
     * @return the value of role.account_status
     *
     * @mbg.generated
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.account_status
     *
     * @param accountStatus the value for role.account_status
     *
     * @mbg.generated
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_spare
     *
     * @return the value of role.role_spare
     *
     * @mbg.generated
     */
    public String getRoleSpare() {
        return roleSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_spare
     *
     * @param roleSpare the value for role.role_spare
     *
     * @mbg.generated
     */
    public void setRoleSpare(String roleSpare) {
        this.roleSpare = roleSpare == null ? null : roleSpare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_portfolio
     *
     * @return the value of role.role_portfolio
     *
     * @mbg.generated
     */
    public Integer getRolePortfolio() {
        return rolePortfolio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_portfolio
     *
     * @param rolePortfolio the value for role.role_portfolio
     *
     * @mbg.generated
     */
    public void setRolePortfolio(Integer rolePortfolio) {
        this.rolePortfolio = rolePortfolio;
    }
}