package com.back.chuilun.entity;

public class SecondPor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.second_por_id
     *
     * @mbg.generated
     */
    private Integer secondPorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_name
     *
     * @mbg.generated
     */
    private String secName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.portfolio_name
     *
     * @mbg.generated
     */
    private String portfolioName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_status
     *
     * @mbg.generated
     */
    private Integer secStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_createtime
     *
     * @mbg.generated
     */
    private Long secCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_updatetime
     *
     * @mbg.generated
     */
    private Long secUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_editor
     *
     * @mbg.generated
     */
    private String secEditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_createman
     *
     * @mbg.generated
     */
    private String secCreateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_por.sec_spare
     *
     * @mbg.generated
     */
    private Integer secSpare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.second_por_id
     *
     * @return the value of second_por.second_por_id
     *
     * @mbg.generated
     */
    public Integer getSecondPorId() {
        return secondPorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.second_por_id
     *
     * @param secondPorId the value for second_por.second_por_id
     *
     * @mbg.generated
     */
    public void setSecondPorId(Integer secondPorId) {
        this.secondPorId = secondPorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_name
     *
     * @return the value of second_por.sec_name
     *
     * @mbg.generated
     */
    public String getSecName() {
        return secName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_name
     *
     * @param secName the value for second_por.sec_name
     *
     * @mbg.generated
     */
    public void setSecName(String secName) {
        this.secName = secName == null ? null : secName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.portfolio_name
     *
     * @return the value of second_por.portfolio_name
     *
     * @mbg.generated
     */
    public String getPortfolioName() {
        return portfolioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.portfolio_name
     *
     * @param portfolioName the value for second_por.portfolio_name
     *
     * @mbg.generated
     */
    public void setPortfolioName(String portfolioName) {
        this.portfolioName = portfolioName == null ? null : portfolioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_status
     *
     * @return the value of second_por.sec_status
     *
     * @mbg.generated
     */
    public Integer getSecStatus() {
        return secStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_status
     *
     * @param secStatus the value for second_por.sec_status
     *
     * @mbg.generated
     */
    public void setSecStatus(Integer secStatus) {
        this.secStatus = secStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_createtime
     *
     * @return the value of second_por.sec_createtime
     *
     * @mbg.generated
     */
    public Long getSecCreatetime() {
        return secCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_createtime
     *
     * @param secCreatetime the value for second_por.sec_createtime
     *
     * @mbg.generated
     */
    public void setSecCreatetime(Long secCreatetime) {
        this.secCreatetime = secCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_updatetime
     *
     * @return the value of second_por.sec_updatetime
     *
     * @mbg.generated
     */
    public Long getSecUpdatetime() {
        return secUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_updatetime
     *
     * @param secUpdatetime the value for second_por.sec_updatetime
     *
     * @mbg.generated
     */
    public void setSecUpdatetime(Long secUpdatetime) {
        this.secUpdatetime = secUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_editor
     *
     * @return the value of second_por.sec_editor
     *
     * @mbg.generated
     */
    public String getSecEditor() {
        return secEditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_editor
     *
     * @param secEditor the value for second_por.sec_editor
     *
     * @mbg.generated
     */
    public void setSecEditor(String secEditor) {
        this.secEditor = secEditor == null ? null : secEditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_createman
     *
     * @return the value of second_por.sec_createman
     *
     * @mbg.generated
     */
    public String getSecCreateman() {
        return secCreateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_createman
     *
     * @param secCreateman the value for second_por.sec_createman
     *
     * @mbg.generated
     */
    public void setSecCreateman(String secCreateman) {
        this.secCreateman = secCreateman == null ? null : secCreateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_por.sec_spare
     *
     * @return the value of second_por.sec_spare
     *
     * @mbg.generated
     */
    public Integer getSecSpare() {
        return secSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_por.sec_spare
     *
     * @param secSpare the value for second_por.sec_spare
     *
     * @mbg.generated
     */
    public void setSecSpare(Integer secSpare) {
        this.secSpare = secSpare;
    }
}