package com.back.chuilun.entity;

public class Studio {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_id
     *
     * @mbg.generated
     */
    private Integer studioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_name
     *
     * @mbg.generated
     */
    private String studioName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_status
     *
     * @mbg.generated
     */
    private Integer studioStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_createtime
     *
     * @mbg.generated
     */
    private Long studioCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_updatetime
     *
     * @mbg.generated
     */
    private Long studioUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_editor
     *
     * @mbg.generated
     */
    private String studioEditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_text
     *
     * @mbg.generated
     */
    private String studioText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_updateman
     *
     * @mbg.generated
     */
    private String studioUpdateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_spare
     *
     * @mbg.generated
     */
    private String studioSpare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_picture
     *
     * @mbg.generated
     */
    private byte[] studioPicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_id
     *
     * @return the value of studio.studio_id
     *
     * @mbg.generated
     */
    public Integer getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_id
     *
     * @param studioId the value for studio.studio_id
     *
     * @mbg.generated
     */
    public void setStudioId(Integer studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_name
     *
     * @return the value of studio.studio_name
     *
     * @mbg.generated
     */
    public String getStudioName() {
        return studioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_name
     *
     * @param studioName the value for studio.studio_name
     *
     * @mbg.generated
     */
    public void setStudioName(String studioName) {
        this.studioName = studioName == null ? null : studioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_status
     *
     * @return the value of studio.studio_status
     *
     * @mbg.generated
     */
    public Integer getStudioStatus() {
        return studioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_status
     *
     * @param studioStatus the value for studio.studio_status
     *
     * @mbg.generated
     */
    public void setStudioStatus(Integer studioStatus) {
        this.studioStatus = studioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_createtime
     *
     * @return the value of studio.studio_createtime
     *
     * @mbg.generated
     */
    public Long getStudioCreatetime() {
        return studioCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_createtime
     *
     * @param studioCreatetime the value for studio.studio_createtime
     *
     * @mbg.generated
     */
    public void setStudioCreatetime(Long studioCreatetime) {
        this.studioCreatetime = studioCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_updatetime
     *
     * @return the value of studio.studio_updatetime
     *
     * @mbg.generated
     */
    public Long getStudioUpdatetime() {
        return studioUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_updatetime
     *
     * @param studioUpdatetime the value for studio.studio_updatetime
     *
     * @mbg.generated
     */
    public void setStudioUpdatetime(Long studioUpdatetime) {
        this.studioUpdatetime = studioUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_editor
     *
     * @return the value of studio.studio_editor
     *
     * @mbg.generated
     */
    public String getStudioEditor() {
        return studioEditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_editor
     *
     * @param studioEditor the value for studio.studio_editor
     *
     * @mbg.generated
     */
    public void setStudioEditor(String studioEditor) {
        this.studioEditor = studioEditor == null ? null : studioEditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_text
     *
     * @return the value of studio.studio_text
     *
     * @mbg.generated
     */
    public String getStudioText() {
        return studioText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_text
     *
     * @param studioText the value for studio.studio_text
     *
     * @mbg.generated
     */
    public void setStudioText(String studioText) {
        this.studioText = studioText == null ? null : studioText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_updateman
     *
     * @return the value of studio.studio_updateman
     *
     * @mbg.generated
     */
    public String getStudioUpdateman() {
        return studioUpdateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_updateman
     *
     * @param studioUpdateman the value for studio.studio_updateman
     *
     * @mbg.generated
     */
    public void setStudioUpdateman(String studioUpdateman) {
        this.studioUpdateman = studioUpdateman == null ? null : studioUpdateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_spare
     *
     * @return the value of studio.studio_spare
     *
     * @mbg.generated
     */
    public String getStudioSpare() {
        return studioSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_spare
     *
     * @param studioSpare the value for studio.studio_spare
     *
     * @mbg.generated
     */
    public void setStudioSpare(String studioSpare) {
        this.studioSpare = studioSpare == null ? null : studioSpare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_picture
     *
     * @return the value of studio.studio_picture
     *
     * @mbg.generated
     */
    public byte[] getStudioPicture() {
        return studioPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_picture
     *
     * @param studioPicture the value for studio.studio_picture
     *
     * @mbg.generated
     */
    public void setStudioPicture(byte[] studioPicture) {
        this.studioPicture = studioPicture;
    }
}