package com.back.chuilun.entity;

public class Visit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visit_id
     *
     * @mbg.generated
     */
    private Long visitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visit_name
     *
     * @mbg.generated
     */
    private String visitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visit_ip
     *
     * @mbg.generated
     */
    private String visitIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visit_time
     *
     * @mbg.generated
     */
    private Long visitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visit_spare
     *
     * @mbg.generated
     */
    private String visitSpare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visit_id
     *
     * @return the value of visit.visit_id
     *
     * @mbg.generated
     */
    public Long getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visit_id
     *
     * @param visitId the value for visit.visit_id
     *
     * @mbg.generated
     */
    public void setVisitId(Long visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visit_name
     *
     * @return the value of visit.visit_name
     *
     * @mbg.generated
     */
    public String getVisitName() {
        return visitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visit_name
     *
     * @param visitName the value for visit.visit_name
     *
     * @mbg.generated
     */
    public void setVisitName(String visitName) {
        this.visitName = visitName == null ? null : visitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visit_ip
     *
     * @return the value of visit.visit_ip
     *
     * @mbg.generated
     */
    public String getVisitIp() {
        return visitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visit_ip
     *
     * @param visitIp the value for visit.visit_ip
     *
     * @mbg.generated
     */
    public void setVisitIp(String visitIp) {
        this.visitIp = visitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visit_time
     *
     * @return the value of visit.visit_time
     *
     * @mbg.generated
     */
    public Long getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visit_time
     *
     * @param visitTime the value for visit.visit_time
     *
     * @mbg.generated
     */
    public void setVisitTime(Long visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visit_spare
     *
     * @return the value of visit.visit_spare
     *
     * @mbg.generated
     */
    public String getVisitSpare() {
        return visitSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visit_spare
     *
     * @param visitSpare the value for visit.visit_spare
     *
     * @mbg.generated
     */
    public void setVisitSpare(String visitSpare) {
        this.visitSpare = visitSpare == null ? null : visitSpare.trim();
    }
}