package com.back.chuilun.entity;

public class WorksCllection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.portfolio_id
     *
     * @mbg.generated
     */
    private Long portfolioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.portfolio_name
     *
     * @mbg.generated
     */
    private String portfolioName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.pstatus
     *
     * @mbg.generated
     */
    private Integer pstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.pcreate_time
     *
     * @mbg.generated
     */
    private Long pcreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.pupdate_time
     *
     * @mbg.generated
     */
    private Long pupdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.poreditor
     *
     * @mbg.generated
     */
    private String poreditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.portfolio_updateman
     *
     * @mbg.generated
     */
    private String portfolioUpdateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works_cllection.portfolio_spare
     *
     * @mbg.generated
     */
    private Integer portfolioSpare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.portfolio_id
     *
     * @return the value of works_cllection.portfolio_id
     *
     * @mbg.generated
     */
    public Long getPortfolioId() {
        return portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.portfolio_id
     *
     * @param portfolioId the value for works_cllection.portfolio_id
     *
     * @mbg.generated
     */
    public void setPortfolioId(Long portfolioId) {
        this.portfolioId = portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.portfolio_name
     *
     * @return the value of works_cllection.portfolio_name
     *
     * @mbg.generated
     */
    public String getPortfolioName() {
        return portfolioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.portfolio_name
     *
     * @param portfolioName the value for works_cllection.portfolio_name
     *
     * @mbg.generated
     */
    public void setPortfolioName(String portfolioName) {
        this.portfolioName = portfolioName == null ? null : portfolioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.pstatus
     *
     * @return the value of works_cllection.pstatus
     *
     * @mbg.generated
     */
    public Integer getPstatus() {
        return pstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.pstatus
     *
     * @param pstatus the value for works_cllection.pstatus
     *
     * @mbg.generated
     */
    public void setPstatus(Integer pstatus) {
        this.pstatus = pstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.pcreate_time
     *
     * @return the value of works_cllection.pcreate_time
     *
     * @mbg.generated
     */
    public Long getPcreateTime() {
        return pcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.pcreate_time
     *
     * @param pcreateTime the value for works_cllection.pcreate_time
     *
     * @mbg.generated
     */
    public void setPcreateTime(Long pcreateTime) {
        this.pcreateTime = pcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.pupdate_time
     *
     * @return the value of works_cllection.pupdate_time
     *
     * @mbg.generated
     */
    public Long getPupdateTime() {
        return pupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.pupdate_time
     *
     * @param pupdateTime the value for works_cllection.pupdate_time
     *
     * @mbg.generated
     */
    public void setPupdateTime(Long pupdateTime) {
        this.pupdateTime = pupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.poreditor
     *
     * @return the value of works_cllection.poreditor
     *
     * @mbg.generated
     */
    public String getPoreditor() {
        return poreditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.poreditor
     *
     * @param poreditor the value for works_cllection.poreditor
     *
     * @mbg.generated
     */
    public void setPoreditor(String poreditor) {
        this.poreditor = poreditor == null ? null : poreditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.portfolio_updateman
     *
     * @return the value of works_cllection.portfolio_updateman
     *
     * @mbg.generated
     */
    public String getPortfolioUpdateman() {
        return portfolioUpdateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.portfolio_updateman
     *
     * @param portfolioUpdateman the value for works_cllection.portfolio_updateman
     *
     * @mbg.generated
     */
    public void setPortfolioUpdateman(String portfolioUpdateman) {
        this.portfolioUpdateman = portfolioUpdateman == null ? null : portfolioUpdateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works_cllection.portfolio_spare
     *
     * @return the value of works_cllection.portfolio_spare
     *
     * @mbg.generated
     */
    public Integer getPortfolioSpare() {
        return portfolioSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works_cllection.portfolio_spare
     *
     * @param portfolioSpare the value for works_cllection.portfolio_spare
     *
     * @mbg.generated
     */
    public void setPortfolioSpare(Integer portfolioSpare) {
        this.portfolioSpare = portfolioSpare ;
    }
}