package com.back.chuilun.entity;

public class Works {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_id
     *
     * @mbg.generated
     */
    private Integer worksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_name
     *
     * @mbg.generated
     */
    private String worksName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.portfolio_name
     *
     * @mbg.generated
     */
    private String portfolioName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.second_por_name
     *
     * @mbg.generated
     */
    private String secondPorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.wcreate_time
     *
     * @mbg.generated
     */
    private Long wcreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.change_time
     *
     * @mbg.generated
     */
    private Long changeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.editor
     *
     * @mbg.generated
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.wstatus
     *
     * @mbg.generated
     */
    private Integer wstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_url
     *
     * @mbg.generated
     */
    private String worksUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_intro
     *
     * @mbg.generated
     */
    private String worksIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_updateman
     *
     * @mbg.generated
     */
    private String worksUpdateman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_spare
     *
     * @mbg.generated
     */
    private String worksSpare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_bintro
     *
     * @mbg.generated
     */
    private String worksBintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_mpic
     *
     * @mbg.generated
     */
    private byte[] worksMpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_pic
     *
     * @mbg.generated
     */
    private byte[] worksPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_id
     *
     * @return the value of works.works_id
     *
     * @mbg.generated
     */
    public Integer getWorksId() {
        return worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_id
     *
     * @param worksId the value for works.works_id
     *
     * @mbg.generated
     */
    public void setWorksId(Integer worksId) {
        this.worksId = worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_name
     *
     * @return the value of works.works_name
     *
     * @mbg.generated
     */
    public String getWorksName() {
        return worksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_name
     *
     * @param worksName the value for works.works_name
     *
     * @mbg.generated
     */
    public void setWorksName(String worksName) {
        this.worksName = worksName == null ? null : worksName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.portfolio_name
     *
     * @return the value of works.portfolio_name
     *
     * @mbg.generated
     */
    public String getPortfolioName() {
        return portfolioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.portfolio_name
     *
     * @param portfolioName the value for works.portfolio_name
     *
     * @mbg.generated
     */
    public void setPortfolioName(String portfolioName) {
        this.portfolioName = portfolioName == null ? null : portfolioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.second_por_name
     *
     * @return the value of works.second_por_name
     *
     * @mbg.generated
     */
    public String getSecondPorName() {
        return secondPorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.second_por_name
     *
     * @param secondPorName the value for works.second_por_name
     *
     * @mbg.generated
     */
    public void setSecondPorName(String secondPorName) {
        this.secondPorName = secondPorName == null ? null : secondPorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.wcreate_time
     *
     * @return the value of works.wcreate_time
     *
     * @mbg.generated
     */
    public Long getWcreateTime() {
        return wcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.wcreate_time
     *
     * @param wcreateTime the value for works.wcreate_time
     *
     * @mbg.generated
     */
    public void setWcreateTime(Long wcreateTime) {
        this.wcreateTime = wcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.change_time
     *
     * @return the value of works.change_time
     *
     * @mbg.generated
     */
    public Long getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.change_time
     *
     * @param changeTime the value for works.change_time
     *
     * @mbg.generated
     */
    public void setChangeTime(Long changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.editor
     *
     * @return the value of works.editor
     *
     * @mbg.generated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.editor
     *
     * @param editor the value for works.editor
     *
     * @mbg.generated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.wstatus
     *
     * @return the value of works.wstatus
     *
     * @mbg.generated
     */
    public Integer getWstatus() {
        return wstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.wstatus
     *
     * @param wstatus the value for works.wstatus
     *
     * @mbg.generated
     */
    public void setWstatus(Integer wstatus) {
        this.wstatus = wstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_url
     *
     * @return the value of works.works_url
     *
     * @mbg.generated
     */
    public String getWorksUrl() {
        return worksUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_url
     *
     * @param worksUrl the value for works.works_url
     *
     * @mbg.generated
     */
    public void setWorksUrl(String worksUrl) {
        this.worksUrl = worksUrl == null ? null : worksUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_intro
     *
     * @return the value of works.works_intro
     *
     * @mbg.generated
     */
    public String getWorksIntro() {
        return worksIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_intro
     *
     * @param worksIntro the value for works.works_intro
     *
     * @mbg.generated
     */
    public void setWorksIntro(String worksIntro) {
        this.worksIntro = worksIntro == null ? null : worksIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_updateman
     *
     * @return the value of works.works_updateman
     *
     * @mbg.generated
     */
    public String getWorksUpdateman() {
        return worksUpdateman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_updateman
     *
     * @param worksUpdateman the value for works.works_updateman
     *
     * @mbg.generated
     */
    public void setWorksUpdateman(String worksUpdateman) {
        this.worksUpdateman = worksUpdateman == null ? null : worksUpdateman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_spare
     *
     * @return the value of works.works_spare
     *
     * @mbg.generated
     */
    public String getWorksSpare() {
        return worksSpare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_spare
     *
     * @param worksSpare the value for works.works_spare
     *
     * @mbg.generated
     */
    public void setWorksSpare(String worksSpare) {
        this.worksSpare = worksSpare == null ? null : worksSpare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_bintro
     *
     * @return the value of works.works_bintro
     *
     * @mbg.generated
     */
    public String getWorksBintro() {
        return worksBintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_bintro
     *
     * @param worksBintro the value for works.works_bintro
     *
     * @mbg.generated
     */
    public void setWorksBintro(String worksBintro) {
        this.worksBintro = worksBintro == null ? null : worksBintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_mpic
     *
     * @return the value of works.works_mpic
     *
     * @mbg.generated
     */
    public byte[] getWorksMpic() {
        return worksMpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_mpic
     *
     * @param worksMpic the value for works.works_mpic
     *
     * @mbg.generated
     */
    public void setWorksMpic(byte[] worksMpic) {
        this.worksMpic = worksMpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_pic
     *
     * @return the value of works.works_pic
     *
     * @mbg.generated
     */
    public byte[] getWorksPic() {
        return worksPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_pic
     *
     * @param worksPic the value for works.works_pic
     *
     * @mbg.generated
     */
    public void setWorksPic(byte[] worksPic) {
        this.worksPic = worksPic;
    }
}