package com.back.chuilun.dao;

import com.back.chuilun.entity.Bannercontrol;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BannercontrolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannercontrol
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannercontrol
     *
     * @mbg.generated
     */
    int insert(Bannercontrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannercontrol
     *
     * @mbg.generated
     */
    Bannercontrol selectByPrimaryKey(Integer bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannercontrol
     *
     * @mbg.generated
     */
    List<Bannercontrol> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannercontrol
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bannercontrol record);

    int updateSorByKey(List<Bannercontrol> list);
}