package com.back.chuilun.dao;

import com.back.chuilun.entity.Model;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated
     */
    int insert(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated
     */
    Model selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated
     */
    List<Model> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Model record);
}