package com.back.chuilun.dao;

import com.back.chuilun.entity.SecondPor;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SecondPorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_por
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer secondPorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_por
     *
     * @mbg.generated
     */
    int insert(SecondPor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_por
     *
     * @mbg.generated
     */
    SecondPor selectByPrimaryKey(Integer secondPorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_por
     *
     * @mbg.generated
     */
    List<SecondPor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_por
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SecondPor record);

    int updateSpareByKey(List<SecondPor> secondPor);

    List<SecondPor> selectByStatus(Integer secStatus);

    List<SecondPor> selectByPname(String portfolioName);

    List<SecondPor> selectBySname(String secName);
}