package com.back.chuilun.dao;

import com.back.chuilun.entity.Visit;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface VisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long visitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbg.generated
     */
    Long insert(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbg.generated
     */
    Visit selectByPrimaryKey(Long visitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbg.generated
     */
    List<Visit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbg.generated
     */
    Long updateByPrimaryKey(Visit record);
}