package com.back.chuilun.dao;

import com.back.chuilun.entity.WorksCllection;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface WorksCllectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_cllection
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long portfolioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_cllection
     *
     * @mbg.generated
     */
    int insert(WorksCllection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_cllection
     *
     * @mbg.generated
     */
    WorksCllection selectByPrimaryKey(Long portfolioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_cllection
     *
     * @mbg.generated
     */
    List<WorksCllection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works_cllection
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorksCllection record);

    int updateSpareByKey(List<WorksCllection> worksCllection);

}