package com.back.chuilun.dao;

import com.back.chuilun.entity.Works;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface WorksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer worksId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated
     */
    int insert(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated
     */
    Works selectByPrimaryKey(Integer worksId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated
     */
    List<Works> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Works record);

    List<Works> selectByName(String keyword);

    List<Works> selectByIntro(String keyword);
}